import { useState, useEffect, useRef } from 'react';
import { base44 } from '@/api/base44Client';
import { Volume2, Square, Loader2 } from 'lucide-react';
import { enforceReadableNarration } from '@/lib/pjNarrationFilter';

export default function NarrationPlayer({ narration, journalEntryId, existingAudioUrl }) {
  const [audioUrl, setAudioUrl] = useState(existingAudioUrl || null);
  const [loading, setLoading] = useState(false);
  const [playing, setPlaying] = useState(false);
  const audioRef = useRef(null);

  // Pick up cached audio URL generated by another party member
  useEffect(() => {
    if (existingAudioUrl && existingAudioUrl !== audioUrl) {
      setAudioUrl(existingAudioUrl);
    }
  }, [existingAudioUrl]);

  async function handlePlay() {
    if (audioUrl) {
      audioRef.current?.play().then(() => setPlaying(true)).catch(() => {});
      return;
    }
    const cleanText = enforceReadableNarration(narration || '').trim();
    if (!cleanText) return;
    setLoading(true);
    try {
      const res = await base44.integrations.Core.GenerateSpeech({
        text: cleanText.slice(0, 5000),
        voice: 'storm'
      });
      if (res?.url) {
        setAudioUrl(res.url);
        // Cache to journal entry so other party members use the same URL
        if (journalEntryId) {
          try {
            await base44.entities.JournalEntry.update(journalEntryId, { audio_urls: [res.url] });
          } catch { /* best-effort caching */ }
        }
        setTimeout(() => {
          audioRef.current?.play().then(() => setPlaying(true)).catch(() => {});
        }, 100);
      }
    } catch { /* silent fail — narration still shows as text */ } finally {
      setLoading(false);
    }
  }

  function handleStop() {
    audioRef.current?.pause();
    setPlaying(false);
  }

  return (
    <div className="flex items-center gap-2">
      {audioUrl && (
        <audio
          ref={audioRef}
          src={audioUrl}
          onPlay={() => setPlaying(true)}
          onEnded={() => setPlaying(false)}
          onPause={() => setPlaying(false)}
        />
      )}
      {loading ? (
        <span className="flex items-center gap-1.5 text-[10px] font-heading tracking-wider text-primary/60">
          <Loader2 className="w-3.5 h-3.5 animate-spin" /> Voice...
        </span>
      ) : playing ? (
        <button
          onClick={handleStop}
          className="flex items-center gap-1.5 text-[10px] font-heading tracking-wider text-primary hover:text-primary/80 transition-colors"
          title="Stop voice narration"
        >
          <Square className="w-3.5 h-3.5 fill-current" strokeWidth={1.5} /> Stop
        </button>
      ) : (
        <button
          onClick={handlePlay}
          className="flex items-center gap-1.5 text-[10px] font-heading tracking-wider text-primary/70 hover:text-primary transition-colors"
          title="Play voice narration"
        >
          <Volume2 className="w-3.5 h-3.5" strokeWidth={1.5} /> Voice
        </button>
      )}
    </div>
  );
}